### PR TITLE
Fix configuration reference typo

### PR DESCRIPTION
**Pull request by Eyjafjallajokull**
Hello,
this PR fixes case in which all data is passed via command line arguments.

### CODE REVIEW

**Comment by szepeviktor** [comment]
Must have been a typo.

**Comment by szepeviktor** [comment]
Could you change https://github.com/puzzle1536/hubic-wrapper-to-swift/blob/master/hubic.py-3#L78-L79 also?

**Comment by Eyjafjallajokull** [comment]
Sure. :)

**Comment by szepeviktor** [comment]
@puzzle1536 Is it Ok to merge?

**Pull request merged**
